export const APP_CONSTANTS = {
  ACTIVITY_FEED: {
    INITIAL_ACTIVITIES_COUNT: 15,
    TIME_UPDATE_INTERVAL_MS: 10000,
    ACTIVITY_STAGGER_DELAY_MS: 100,
  },

  EVENT_TIMING: {
    MIN_RANDOM_DELAY_MS: 3000,
    MAX_RANDOM_DELAY_RANGE_MS: 2000,
  },

  GESTURE: {
    ACTIVE_OFFSET_X_MIN: -10,
    ACTIVE_OFFSET_X_MAX: 10,
    SWIPE_THRESHOLD_PX: -100,
    SWIPE_DISMISS_TRANSLATION_PX: -400,
    OPACITY_CALCULATION_DIVISOR: 200,
  },

  ANIMATION: {
    FADE_IN_DURATION_MS: 400,
    LAYOUT_TRANSITION_DURATION_MS: 250,
    DISMISS_DURATION_MS: 200,
    BADGE_FADE_DURATION_MS: 300,
  },

  OPACITY: {
    MIN: 0,
    MAX: 1,
  },

  FLATLIST: {
    MAX_TO_RENDER_PER_BATCH: 10,
    WINDOW_SIZE: 10,
    INITIAL_NUM_TO_RENDER: 15,
    UPDATE_CELLS_BATCHING_PERIOD_MS: 50,
  },

  UI: {
    ICON_BACKGROUND_OPACITY: "20",
  },
} as const;

export type AppConstants = typeof APP_CONSTANTS;
